<body>
    <div class="container">
        <a href="<?= "?page=adminlist" ?>" class="btn btn-primary m-1">Admin List</a>
    </div>

    <h2 class="text-center mb-5">Admin Add Picture</h2>
    <div class="container">
        <form method="POST" action="">
            <div class="mb-3">
                <label for="source" class="form-label">Source image (url)</label>
                <input type="text" name="source" class="form-control" id="source" placeholder="https://....">
            </div>
            <div class="mb-3">
                <label for="title" class="form-label">Titre</label>
                <input type="text" name="title" class="form-control" id="title" placeholder="Titre de l'article">
            </div>
            <div class="mb-3">
                <label for="description" class="form-label">Description</label>
                <textarea class="form-control" name="description" id="description" rows="5" placeholder="Rédiger article"></textarea>
            </div>
            <div class="mb-3">
                <label for="author" class="form-label">Auteur</label>
                <input type="text" name="author" class="form-control" id="author" placeholder="Nom de l'auteur">
            </div>

            <button type="submit" name="submit" class="btn btn-primary">Publier</button>

    </div>
    </form>
    <div class="container">
        <?php if (!empty($message)) : ?>
            <div class="alert <?php echo (strpos($message, 'bien été envoyé') !== false) ? 'alert-success' : 'alert-danger'; ?>">
                <?php echo $message; ?>
            </div>
        <?php endif; ?>
    </div>

</body>

</html>