<style>


</style>

<h1 class="text-center">Search</h1>
<h2 class="text-center">Found <?= count($results) ?> result(s)</h2>
<section class="row  mt-4">
    <?php foreach ($results as $image) :
        $id = $image['id'];
        $description = $image['description'];
        $source = $image['source'];
        $title = $image['title'];
        $author = $image['author'];
        $created_at = $image['created_at'];
    ?>
        <div class="container d-flex justify-content-center mt-1">
            <article>
                <div class="card" style="width: 100%;">
                    <div class="row no-gutters">
                        <div class="col-sm-5">
                            <a href="<?= '?page=details&id=' . $id ?>">
                                <img src=" <?= $source ?>" class="card-img-top img-fluid" alt="<?= $description ?>">
                            </a>
                        </div>
                        <div class="col-sm-7 row text-center">
                            <div class="card-body col align-self-center ">
                                <a href="<?= '?page=details&id=' . $id ?>" class="text-dark text-decoration-none">
                                    <h5 class=" card-title"><?= $title . ' by ' . $author ?></h5>
                                </a>
                                <p class="card-text">Posté le : <?= $created_at ?></p>
                                <p class="card-text">By <?= $author ?></p>
                                <a href="<?= '?page=details&id=' . $image['id'] ?> " class="btn btn-secondary">Read more</a>
                            </div>
                        </div>
                    </div>
                </div>
            </article>
        </div>
    <?php endforeach ?>
</section>