<article class="container">
  <h1 class="text-center mb-5"><?php echo htmlspecialchars($results['title']); ?></h1>
  <div class="row justify-content-center align-items-center">
    <div class="card mb-5" style="width: 50rem">
      <img class="card-img-top" src="<?php echo htmlspecialchars($results['source']); ?>" alt="Card image cap">
      <div class="card-body d-flex justify-content-around flex-column text-center">
        <h5 class="card-title">By <?php echo htmlspecialchars($results['author']); ?></h5>
        <p class="card-text">Your article content here...</p>
        <p class="card-text">More content here...</p>
        <div class="d-flex justify-content-around">
          <p>Published : <?php echo htmlspecialchars($results['created_at']); ?></p>
        </div>
      </div>
    </div>
  </div>
</article>

<h2>Commentaires</h2>

<?php
if (isset($_SESSION['userinfos'])) {
  //  user session active
?>
  <form method="post">
    <div>
      <label for="author">Auteur</label><br />
      <input type="text" id="author" name="author" value="<?= $_SESSION['userinfos']['name'] ?>" />
    </div>
    <div>
      <label for="comment">Commentaire</label><br />
      <textarea id="comment" name="comment"></textarea>
    </div>
    <div>
      <input type="submit" name="submitComment" value="Ajouter un commentaire" />
    </div>
  </form>
<?php
} else {
  echo "Connectez-vous pour ajouter un commentaire.";
}
?>



<section style="background-color: #eee;">
  <div class="container my-5 py-5">
    <div class="row d-flex justify-content-center">
      <div class="col-md-12 col-lg-10">
        <div class="card text-dark">

          <div class="card-body p-4">
            <h4 class="mb-0">Recent comments</h4>
            <p class="fw-light mb-4 pb-2">Latest Comments section by users</p>

            <div class="d-flex flex-start">
                <?php
                foreach ($comments as $comment) {
                ?>
              <div>

                  <h6 class="fw-bold mb-1"><?= htmlspecialchars($comment['author']) ?></h6>
                  <div class="d-flex align-items-center mb-3">
                    <p class="mb-0">
                      le <?= $comment['french_creation_date'] ?>
                    </p>
                    <a href="#!" class="link-muted"><i class="fas fa-pencil-alt ms-2"></i></a>
                    <a href="#!" class="link-muted"><i class="fas fa-redo-alt ms-2"></i></a>
                    <a href="#!" class="link-muted"><i class="fas fa-heart ms-2"></i></a>
                  </div>
                  <p class="mb-0">
                    <?= nl2br(htmlspecialchars($comment['comment'])) ?>
                  </p>
                  
              </div>
            </div>
            <hr class="my-3" />
            <?php } ?>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>