<div class="container mt-5">
    <?php if (!empty($successMessage)) : ?>
        <div class="alert alert-success" role="alert">
            <?php echo $successMessage;
            ?>
        </div>
        <script>
            setTimeout(function() {
                document.querySelector('.alert-success').style.display = 'none';
            }, 1000);
        </script>
    <?php endif; ?>

    <?php if (!empty($errorMessage)) : ?>
        <div class="alert alert-danger" role="alert">
            <?php echo $errorMessage; ?>
        </div>
        <script>
            setTimeout(function() {
                document.querySelector('.alert-danger').style.display = 'none';
            }, 3000);
        </script>
    <?php endif; ?>



    <?php if ($showForm) { ?>
        <form method="post">
            <div class="mb-3">
                <label for="mail" class="form-label">Email</label>
                <input type="email" class="form-control" id="mail" name="mail" aria-describedby="mail-help" placeholder="you@example.com">
                <div id="mail-help" class="form-text">L'email utilisé lors de la création de compte.</div>
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">Mot de passe</label>
                <input type="password" class="form-control" id="password" name="password">
            </div>
            <button type="submit" name="submit" class="btn btn-primary">Envoyer</button>
        </form>
    <?php }
    ?>


   
</div>