<h1 class="text-center mb-5">HOME</h1>
<div class="container">
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <?php
            $count = 0;
            foreach (array_reverse($results) as $key => $image) :
                $id = $image['id'];
                $description = $image['description'];
                $source = $image['source'];
                $title = $image['title'];
                $author = $image['author'];
                $created_at = $image['created_at'];
                $updated_at = $image['updated_at'];
                if ($count < 3) {
            ?>
                    <div class="carousel-item <?php if (array_key_first($results) === $key) echo "active"; ?>">
                        <img class="d-block w-100" src="<?= $source ?>" style="aspect-ratio: 16/9">
                    </div>
            <?php $count++;
                }
            endforeach;
            ?>

        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>