<h1 class="text-center">ADMIN LIST</h1>
<div class="container mb-4">
  <a href="<?= "?page=addPicture" ?>" class="btn btn-primary m-1">Add Picture</a>
</div>

<table class="table table-striped  w-auto">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Source</th>
      <th scope="col">Title</th>
      <th scope="col">Author</th>
      <th scope="col">Description</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($results as $image) : ?>
      <tr>
        <th scope="row"><?= $image['id'] ?></th>
        <td><img width="80" src="<?= $image['source'] ?>" alt="<?= $image['title'] ?>"></td>
        <td><?= $image['title'] ?></td>
        <td><?= $image['author'] ?></td>
        <td><?= $image['description'] ?></td>

        <td>
          <a href="#" class="btn btn-warning m-1">Update</a>
          <a href="#" class="btn btn-danger m-1">Delete</a>
        </td>
      </tr>
    <?php endforeach ?>
  </tbody>
</table>