<h1 class="text-center">ADMIN LIST</h1>
<div class="container mb-4">
  <a href="<?= "?page=admin_add" ?>" class="btn btn-primary m-1">Add Picture</a>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Source</th>
      <th scope="col">Title</th>
      <th scope="col">Author</th>
      <th scope="col">Description</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($results as $image) : ?>
      <tr>
        <th scope="row"><?= $image['identifier'] ?></th>
        <td><img width="80" src="<?= $image['source'] ?>" alt="<?= $image['title'] ?>"></td>
        <td><?= $image['title'] ?></td>
        <td><?= $image['author'] ?></td>
        <td><?= $image['description'] ?></td>

        <td>
          <a href="?page=admin_update&id=<?= $image['identifier'] ?>" class="btn btn-success m-1">Update</a>
          <a href="?page=admin_delete&id=<?= $image['identifier'] ?>" class="btn btn-danger m-1">Delete</a>
          <br>
          <a href="javascript:deletePicture(<?= $image['identifier'] ?>)" class="btn btn-warning m-1">Delete? (confirmJS)</a>
        </td>
      </tr>
    <?php endforeach ?>
  </tbody>
</table>
<script>
  function deletePicture(id) {
    const question = window.confirm("Are you sure you want to delete " + id + " ?");
    if (question) {
      location.href = "?page=admin_delete&id=" + id;
    }
  }
</script>