<h1 class="mb-3 text-center">Admin Update Picture</h1>
<form method="POST" action="?page=admin_update&id=<?= $id ?>">
    <div class="mb-3">
        <label for="title" class="form-label">Title</label>
        <input value="<?= $image['title'] ?>" type="text" class="form-control" name="title" id="title" placeholder="Title">
    </div>
    <div class="mb-3">
        <label for="description" class="form-label">Description</label>
        <input value="<?= $image['description'] ?>" type="text" class="form-control" name="description" id="description" placeholder="Description">
    </div>
    <div class="mb-3">
        <label for="source" class="form-label">Source</label>
        <input value="<?= $image['source'] ?>" type="text" class="form-control" name="source" id="source" placeholder="URL Source">
    </div>
    <div class="mb-3">
        <label for="author" class="form-label">Author</label>
        <input value="<?= $image['author'] ?>" type="text" class="form-control" name="author" id="author" placeholder="Author">
    </div>
    <div class="mb-3">
        <input type="submit" class="btn btn-primary" name="submit" value="Update Picture">
    </div>
</form>